import "./Contact.scss"

function Contact() {
    return (
        <div id="contact">
            <h2>Contact</h2>

            Lorem ipsum dolor, sit amet consectetur adipisicing elit. Rem autem ut veniam et consequuntur illum ducimus recusandae, nostrum, voluptas quidem tempore cupiditate suscipit. Voluptas tempore facilis in qui hic repellendus suscipit! Iure nihil, id praesentium magnam, consequuntur eaque distinctio tempore numquam animi quas placeat nam voluptates voluptate hic sequi nesciunt debitis, illo quod. Ducimus dolorem, qui architecto enim aperiam assumenda eaque aut doloribus aliquam delectus amet cupiditate, commodi at facere. Possimus tempore, commodi reprehenderit sapiente et facere laboriosam labore voluptatum dolore dignissimos veniam rerum odit perferendis minima alias, quod explicabo quis velit. Nam accusamus cum alias magni deleniti! Quo quas optio cum! Accusamus magnam ducimus consequatur placeat qui repellendus quas libero nam, dolore architecto id error, labore perferendis perspiciatis voluptas praesentium incidunt inventore enim? Qui optio ipsum repellat consequatur doloribus deleniti dolor. Distinctio suscipit dicta veritatis consequatur porro deserunt saepe repudiandae? Libero magni, numquam animi facilis esse cum, eaque provident accusamus unde ea in sed id sequi hic asperiores beatae magnam mollitia! Atque minima perferendis sequi? Voluptate, a. Quia, veritatis inventore asperiores id placeat sed sequi! Facere quasi amet accusamus. Incidunt ducimus nemo provident voluptas sequi quibusdam neque delectus, dolorum, ipsam sed odit magnam eveniet officia id facere dolorem nobis omnis fugiat natus porro, sit iusto ab placeat cumque? Inventore unde ex ullam natus, quam et, qui magni ipsa nisi officia incidunt aliquam? Quia nesciunt magnam velit corporis non consectetur itaque, consequatur labore voluptatibus ducimus, sequi vitae perspiciatis. Atque repellat exercitationem enim voluptate. Expedita natus cum at omnis ratione, voluptates sequi similique! Ut, totam eveniet? Ducimus, ad officiis laborum temporibus iure quod labore tempore repellat? Mollitia cupiditate omnis sit, beatae nemo praesentium quasi, dolor unde numquam pariatur, earum placeat debitis officia. Aliquid perferendis eaque quam repellendus unde sapiente possimus. Quo vitae, rerum consectetur adipisci impedit sapiente optio sunt. Rerum, delectus! Voluptate illo dolorem nam. Hic, magnam! Modi unde est aperiam sed. Voluptas fugiat quae non qui. Autem voluptate unde quas assumenda dignissimos illo tenetur, sed corporis. Nemo maxime delectus doloremque, soluta esse eaque, illo accusantium exercitationem recusandae natus nihil similique. Ratione deserunt rerum culpa repudiandae officiis fugiat nisi aut quisquam iusto voluptatum delectus sit veniam dolorum, fuga inventore quasi dicta. Pariatur aliquam quaerat veritatis et, corrupti velit rem ducimus iure fuga, vel in! Facilis saepe aliquid soluta non inventore repudiandae ipsum doloremque quasi, distinctio esse dolores libero deleniti pariatur, eius in voluptatem commodi, possimus quos suscipit. Non facere unde eaque.
        </div>
    )
}

export default Contact;